/// Generated by AssetsRefGenerator on 2021/09/30
class Res {
  static const String bg = "assets/images/bg.png";
  static const String logo = "assets/images/logo.png";
  static const String on1 = "assets/images/on1.png";
  static const String on2 = "assets/images/on2.png";
  static const String on3 = "assets/images/on3.png";
  static const String shape = "assets/images/shape.png";
}
